#!/usr/bin/env bash

# get the directory where the this running script is located
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") &> /dev/null && pwd)

dry_run="0"
filter=""

while [ "$#" -gt 0 ]; do
    if [ "$1" == "--dry" ]; then
        dry_run="1"
    else
	filter="$1"
    fi
    shift
done

log() {
    if [ "$dry_run" == "1" ]; then
        echo "[DRY RUN]: $1"
    else
        echo "$1"
    fi
}

# find all files in $script_dir/runs that are executable
scripts=$(find $script_dir/runs -mindepth 1 -maxdepth 1 -type f -executable)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
	log "FILTERED $script"
	continue
    fi
    
    log "RUNNING SCRIPT $script"

    if [ "$dry_run" == "0" ]; then
	$script
    fi
done
